### ISSUE TITLE
Timezone handling

### ISSUE THREAD

**Issue by blvrd** [blvrd/volition#4]
Users should be able to access their todo list for the day until midnight their time.

**Comment by jorgeegomez** [comment]
@garrettqmartin8 Is it in any way possible to evaluate the day after midnight? I find it frustrating to not have access to the tasks when I miss this "deadline" even by a couple of minutes. I'm not sure why, but today I lost the tasks I'd planned and completed for the day when I didn't review it on time. Thanks.
